name: macOS Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to the latest v3 version

      - name: Set up Python
        uses: actions/setup-python@v4  # Updated to the latest v4 version
        with:
          python-version: '3.x'  # Adjust to your preferred version

      - name: Install Dependencies
        run: |
          brew install pkgbuild
          # Add more dependencies as needed

      - name: Build macOS Package
        run: |
          sudo pkgbuild --root /path/to/your/files \
          --identifier com.github.rajchat-hub.pythoyo \
          --version 1.0 \
          --install-location /Applications \
          PythOyO.pkg
          
      - name: Upload artifact
        uses: actions/upload-artifact@v3  # Updated to the latest v3 version
        with:
          name: macOS-pkg
          path: PythOyO.pkg
